/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.67.0
  Forc version: 0.46.1
  Fuel-Core version: 0.20.8
*/

export type { CounterAbi } from './CounterAbi';

export { CounterAbi__factory } from './factories/CounterAbi__factory';
