export const predicates = {
  'verification-predicate': {
    abi: {
  "types": [
    {
      "typeId": 0,
      "type": "b256",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "bool",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "struct EvmAddress",
      "components": [
        {
          "name": "value",
          "type": 0,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [
        {
          "name": "witness_index",
          "type": 3,
          "typeArguments": null
        }
      ],
      "name": "main",
      "output": {
        "name": "",
        "type": 1,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [
    {
      "name": "SIGNER",
      "configurableType": {
        "name": "",
        "type": 2,
        "typeArguments": []
      },
      "offset": 1896
    }
  ]
},
    bytecode: base64ToUint8Array('dAAAA0cAAAAAAAAAAAAHGF38wAEQ//MAGuxQAJEABjhxRAADYUkRAXZIAAJhQRENdAAAB3JMAAITSSTAWkkgAXZIAAJhQREfdAAAASQAAABdQQAAXU/wDhBNMwBdU/APEFFDAF1f8A8QXXMAYUEDAlBHtfhySABAKEUEgFBDtfgaRAAAckgAICjtFIBQR7AgckgAIChFNIBQR7BAckgAIChFdIBQR7RIckgAYChHtIBQR7RIUEu0KHJMACAoSUTAUEu0KF1P8AgQTRTAUFO0SFBRQCBdV/AJXVvwCChNFUBBSUWAUEe0KFBLsKByTAAgG0wEwBBNJMByUAAgKE11AHJMACAbTBTAEE0kwHJQACAoTXUAUE+x0HJQAEAoTSUAUEu1kHJQAEAoSTUAUEu1kFBPsQhyUABAKE0FAFBDsoByUAAgKEEVAD5JNAAaQIAAE0EAQHZAAApQQ7I4X0AAAFBHtZBQSQAIckwAQChJFMBQS7N4ckQASChJBEB0AAAHUEOxiF9AEABQRQBAX0QAAFBLs3hyRABIKEkEQFBDtShyRABIKEEkQFBDsqByRABIKEEkQFBDs3hdQQAAE0EAQHZAADtQQ7UoUEey6HJIAEgoRQSAUEO1KF1BAAATQQAAdkAAATYAAABQQ7LoUEEACFBHtKhySABAKEUEgFBDtKhyRAAgG0QEQBBFBEBQQ7SockgAIBtIFIAQSQSAUEOxSHJMACAoQRTAUEEAIHJEACAoQSRAUEOxSFBHs1ga6QAAGuUQACD4MwBY++ACUPvgBHQAAEoaR9AAUEu1cHJAACAoSRQAUEOyEF9AAABQR7VwUEu1CHJMACAoSRTAUEe1CHBEAAxQR7UIUEuwgHJMACAoSRTAUEUACHJMACAoRSTAUEuzwHJEACgoSQRAdAAAClBDsqBQQQBAUEew4F9EEABQSRAgckwACChJBMBQS7PAckAAKChJFABQQ7XQckQAKChBJEBQQ7PAXUEAABNBAAAaRBAAdkAAARpEAAB2RAABdAAAHFBDtdBQR7MwckgAKChFBIBQQ7XQXUEAABNBAAB2QAABNgAAAFBDszBQQQAIUEe06HJIACAoRQSAUEOwYF1H8BAQRRMAckgAIChBFIBQR7ToUEuz6HJMACAoSQTAUEO0CHJMACAoQRTAoUEkIHZAAAEkAAAAJAQAABrwUACRAAAwX/EAAF/xEAFf8SACX/EwA1/xQARf87AFGuxQAJEAADgaQ6AAGkeQABpL4ABdT/APEE0zABpQAAAmUAAAGlBwAF/tQABQU7AIX1AAAFBTsBBfUAAAGukAABrnsAAg+DMAWPvgAlD74AR0AAAWUEOwGHJQACAoQTUAUEOwGF1PsABQU7AQXVFAAEFBNQByTAAgKEUEwBr1EACSAAA4GvkgAFnwUDBdQ8AAXUfAAV1LwAJdT8ADXVPABF3vwAWSAAAwSvgAABrwUACRAABYX/EAAF/xEAFf8SACX/EwA1/xQARf8VAFX/FgBl/xcAdf8YAIX/GQCV/zsAoa7FAAkQAAQBpjoAAaX5AAGlvgAF1D8AkmQAAAGmRwAHJAACAo7YQAGkOwAF1FAABQSQAIXUkgAFBNABBdTTAAUEEAGF1BAABfZRAAX2UgAV9lMAJfZQADXUPwCRNBAAB2QAA0UEFwEF1BAAATQQAAdkAAJ1BBcBBdQQAAXUfwCRBBBEBQRXAQXUUQAF1JcABQTXAIXU0wABVRBMB2UAABdAAAByZAAAAaUHAAFVUwAHZUAAF0AAABKFEkwBpJQABfXSAAGlAAAF1L8AkWSUSAdkgAB1BFcAhfRQAAUEVwEF9FAAAaQAAAJkAAAHQAABFdSXAAEEkkQBBJJQAQTZUAXE0wAF5JMAAQUUBAdQAAEF9dkABQQXAIXUfwCV9BEABQQXAQXUfwCV9BEAAaQAAAJkAAAFBBgCBdR/AJJkQAABpgcABQR7AgckgAIChFBIBdQRAAUEkQCF1JIABQTRAQXU0wAFBFEBhdRRAAX2EAAF9hIAFfYTACX2EQA11D8AkTQQAAdkAANFBBcBBdQQAAE0EAAHZAACdQQXAQXUEAAF1H8AkQQQRAUEVwEF1FEABdSXAAUE1wCF1NMAAVUQTAdlAAAXQAAAcmQAAAGlBwABVVMAB2VAABdAAAAShRJMAaSUAAX10gABpQAABdS/AJFklEgHZIAAdQRXAIX0UAAFBFcBBfRQAAGkAAACZAAAB0AAARXUlwABBJJEAQSSUAEE2FAFxNMABeSTAAEFFAQHUAABBfXYAAUEFwCF1H8AlfQRAAUEFwEF1H8AlfQRAAGkAAACZAAAAa9AAAkgAAQBr5YABZ8FBYXUPAAF1HwAFdS8ACXU/AA11TwARdV8AFXVvABl1fwAddY8AIXWfACV3vwAqSAABYSvgAABlFdGhlcmV1bSBTaWduZWQgTWVzc2FnZToKMzIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHGAAAAAAAAAc4AAAAAAAAB2g='),
  },

};

function base64ToUint8Array(base64: string) {
  var binaryString = atob(base64);
  var bytes = new Uint8Array(binaryString.length);
  for (var i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
  }
  return bytes;
}
